service: greeter-api
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    config: node_modules/@sat/serverless-esbuild-config/config.js

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SENTRY_DSN: ${env:SENTRY_DSN_GREETER_API, env:SENTRY_DSN}
    SENTRY_ENVIRONMENT: ${sls:stage}

functions:
  greeter-endpoint:
    handler: src/index.default
    environment:
      FUNCTION_NAME: greeter-endpoint
    events:
      - httpApi:
          path: /
          method: post
  alternative-endpoint:
    handler: src/alt.default
    environment:
      FUNCTION_NAME: alternative-endpoint
    events:
      - httpApi:
          path: /
          method: get
