service: graphql-api
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    config: node_modules/@sat/serverless-esbuild-config/config.js

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SENTRY_DSN: ${env:SENTRY_DSN_GRAPHQL_API}
    SENTRY_ENVIRONMENT: ${sls:stage}

functions:
  graphql-endpoint:
    handler: src/index.default
    environment:
      FUNCTION_NAME: graphql-endpoint
    events:
      - httpApi:
          path: /
          method: post
