service: sat-api
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    packager: pnpm
    minify: true
    sourcemap: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  graphql-endpoint:
    handler: src/index.default
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
    events:
      - httpApi:
          path: /
          method: post
