name: Deploy Services
run-name: Services' deploy to dev by ${{ github.actor }}

on:
  push:
    branches:
      - master

env:
  CI: true
  NODE_ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    strategy:
      matrix:
        service-name: ["graphql-api", "greeter-api"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PNPM
      uses: pnpm/action-setup@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install

    - name: Cache Turborepo, Prettier and ESLint artifacts
      uses: actions/cache@v3
      with:
        path: |
          ./node_modules/.cache
          ./packages/*/node_modules/.cache
          ./packages/*/.eslintcache
          ./apps/*/node_modules/.cache
          ./apps/*/.eslintcache
        key: ${{ runner.os }}-turborepo-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Lint
      run: pnpm lint

    - name: Typecheck
      run: pnpm typecheck

    - name: Deploy
      run: pnpm -F ${{ matrix.service-name }} run build
      env:
        SENTRY_DSN: ${{ fromJSON(vars.SERVICES_SENTRY_DSN_VALUES)[matrix.service-name] }}
